"""
Django settings for django_blog project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$$a!hxopok+h-&)vb=7yqk9ahg349rg&a*c6lkaduzz)z*3fvo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'aplicaciones.blog',
    'import_export',
    'django_ckeditor_5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_blog.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-pe'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # Crea esta carpeta en la raíz
# Se recomienda usar 'staticfiles' como carpeta de destino para collectstatic
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# 2. Archivos de Medios (MEDIA): Para las imágenes que subas con CKEditor
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # Crea esta carpeta en la raíz de tu proyecto

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ------------------- CONFIGURACIÓN DE CKEDITOR 5 -------------------

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            # ----- Bloque 1: Deshacer/Rehacer y Estructura -----
            'undo', 'redo', '|', 
            'heading', '|', 
            
            # ----- Bloque 2: Fuentes y Estilos (Requiere Plugins) -----
            'fontFamily', 'fontSize', '|',  # Opciones de fuente y tamaño
            'fontColor', 'fontBackgroundColor', '|', # Opciones de color
            'bold', 'italic', 'underline', 'strikethrough', 'removeFormat', '|',
            
            # ----- Bloque 3: Alineación, Listas y Sangría -----
            'alignment', 'bulletedList', 'numberedList', 'outdent', 'indent', '|',
            
            # ----- Bloque 4: Inserción de Medios y Avanzado -----
            'link', 'imageUpload', 'insertTable', 'blockQuote', 'codeBlock', 'specialCharacters', '|',
            
            # ----- Bloque 5: Modo HTML (Esencial) -----
            'sourceEditing', 
        ],
        'height': '500px',
        
        # -------------------------------------------------------------------
        # ¡IMPORTANTE! Debes cargar estos plugins para que los botones funcionen
        # -------------------------------------------------------------------
        'addPlugins': [
            'Alignment',
            'Font', 
            'FontBackgroundColor', 
            'FontColor', 
            'FontSize', 
            'FontFamily',
        ],
        
        # Configuración de imágenes (la mantenemos)
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft', 'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side'],
        },
    },
}